# @remove-file-web
on:
  pull_request:
    paths:
      - packages/common/**
      - packages/web/**
      - packages/pulumi-web-build/**
      - packages/pulumi-web/**
jobs:
  preview:
    name: Pulumi Preview CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn --cwd packages/common build
      # Run `yarn --cwd packages/web build` instead of pulumi up on pulumi-web-build
      # because pulumi up requires a Pulumi stack is configured for this branch
      - run: yarn --cwd packages/web build
      - uses: docker://pulumi/actions
        with:
          args: preview
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: pr
          PULUMI_ROOT: packages/pulumi-web
          # Yarn is required for workspaces
          USE_YARN: true
  test:
    name: Node.js CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn --cwd packages/common build
      - run: yarn --cwd packages/web test
        env:
          CI: true
