on:
  push:
    branches:
      - master
    paths:
      - packages/server/**
      - packages/pulumi-server/**
jobs:
  up:
    name: Pulumi Update CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - uses: docker://pulumi/actions
        with:
          args: up --yes
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CI: up
          PULUMI_ROOT: packages/pulumi-server
          # Yarn is required for workspaces
          USE_YARN: true
